### ISSUE TITLE
'models/tmr_humanml3d_guoh3dfeats/latents/humanml3d_all_unit.npy' file missing

### ISSUE THREAD

**Issue by ryanhoo** [Mathux/TMR#11]
After I train and prepare all the data by following the readme, when I run python `app.py`, there is an error:

```
Traceback (most recent call last):
  File "/app/TMR/app.py", line 244, in <module>
    unit_motion_embs, keyids_index, index_keyids = load_unit_embeddings(
  File "/app/TMR/demo/load.py", line 16, in load_unit_embeddings
    motion_embs = torch.from_numpy(np.load(unit_emb_path)).to(device)
  File "/usr/local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'models/tmr_humanml3d_guoh3dfeats/latents/humanml3d_all_unit.npy'
```

Need help pls.

**Comment by Mathux** [comment]
Hello @ryanhoo,

Did you run this command before running ``app.py`` ?
```bash
python encode_dataset.py run_dir=RUN_DIR
```
